### ISSUE TITLE
Update recast?

### ISSUE THREAD

**Issue by developit** [mariusGundersen/amd-optimize#4]
This project is using Recast 0.5.x, and the current version is 0.10.10.  I'm fairly sure it's causing an issue I'm seeing where recast can't load the `ast-types` module.

**Comment by mariusGundersen** [comment]
sure, can you create a pull-request?

**Comment by developit** [comment]
I'll try in a bit, currently seeing if WebPack is a better fit

**Comment by developit** [comment]
Looks like @CiberNorge did it for me! /Thanks

**Comment by mariusGundersen** [comment]
Yup, it didn't work anymore, so had to be updated!
